# Exercício de aquecimento

- Crie uma lista de 1 milhão de elementos, onde cada elemento tem numeros aleatorios entre 1 e 20
- Agora calcule a soma de todos os elementos dessa lista
- Identifique o tempo que demora calcular a soma (pode usar a biblioteca ``time``)

In [2]:
list(range(3))

[0, 1, 2]

In [4]:
lista = []

lista.append(12)
lista.append(13)
lista.append(14)

lista 

[12, 13, 14]

In [20]:
import random

random.randint(1, 20)

18

In [25]:
lista = [1,2,3,4]

sum(lista)

10

In [35]:
#time

import time

time.time()

1698708878.122854

In [180]:
import random
import time 

# Crie uma lista de 1 milhão de elementos, onde cada elemento tem numeros aleatorios entre 1 e 20
tamanho_lista = 50000000

lista = []

for indice in range(tamanho_lista):
    valor = random.randint(1, 20)
    lista.append(valor)

# Agora calcule a soma de todos os elementos dessa lista
# Identifique o tempo que demora calcular a soma

hora_inicial = time.time()
soma_total = sum(lista)
hora_final = time.time()

tempo_total = hora_final - hora_inicial

# criando a lista numpy
lista_np = np.array(lista)


print(f"O tempo total para calcular a soma usando listas foi: {tempo_total}")


hora_inicial = time.time()
soma_total = np.sum(lista_np)
hora_final = time.time()

tempo_total_np = hora_final - hora_inicial

print(f"O tempo total para calcular a soma usando listas de numpy foi: {tempo_total_np}")

proporcao = tempo_total / tempo_total_np

print(f"A lista de numpy foi {proporcao} vezes mais rapida.")
    
#print(lista)

O tempo total para calcular a soma usando listas foi: 0.12343883514404297
O tempo total para calcular a soma usando listas de numpy foi: 0.012473344802856445
A lista de numpy foi 9.896209645048454 vezes mais rapida.


# NumPy
-------

Muitos trabalhos aplicados em empresa envolvem cálculos matemáticos avançados, e por isso precisam se apoiar em alguma biblioteca. Quer trabalhemos com estatística, aprendizado de máquina, processamento de imagem, de texto, de áudio, com otimização, ou até simulação de sistemas reais, uma boa biblioteca matemática é fundamental. 

No Python, a biblioteca [**NumPy**][NumPy_docs] (abreviação para *Numerical Python* [\[2\]](#2)) faz esse papel. Ela é uma poderosíssima biblioteca matemática, e é um dos cernes da computação científica e ciência de dados em Python.

Os cálculos realizados pelo NumPy são baseados em operações com os chamados Arrays Multidimensionais (em matemática, chamamos de vetores, matrizes ou tensores). Esses objetos fundamentais da biblioteca são basicamente "listas de listas de listas de ...". O NumPy implementa operações nesses objetos de forma eficiente, em uma linguagem de mais baixo nível (linguagem C), o que confere a eles enorme velocidade e eficiência. Nós aproveitamos essa eficiência através da interface amigável que a biblioteca possui em Python.

Quando organizamos nosso código para aproveitar as operações do NumPy, é comum dizermos que nós "vetorizamos" o nosso código. Isso significa que evitamos loops explícitos no código Python, e reescrevemos tudo usando os arrays do NumPy. Assim, conseguimos aproveitar toda a velocidade das operações "vetorizadas", acelerando muito o nosos código.

A esmagadora maioria das bibliotecas de Python para computação científica, processamento de dados e ciência de dados (como por exemplo, SciPy, pandas, scikit-learn e statsmodels) se apoiam nas funcionalidades do NumPy [\[2\]](#2). 

1. [Instalação](#1instalacao)
2. [Introdução ao NumPy](#2introducao)
    1. [Cuidados iniciais: Como copiar arrays](#21copiar)
    2. [Propriedades de ndarrays](#22propriedades)
    3. [Acessando e modificando elementos (Indexing & Slicing)](#23indexing)
    4. [Máscara Booleana e Seleção Avançada](#24boolmask)
    5. [Métodos built-in de criação de arrays](#25arraycreate)
O argumento é o formato do ndarray resultante. [](#)
O argumento é o formato do array resultante. [](#)
3. [Matemática com NumPy](#3matematica)
    1. [Broadcasting](#31broadcasting)
    2. [Funções matemáticas](#32funcoesmath)
4. [Álgebra Linear e Estatística básica](#4algelinestat)
    1. [Álgebra Linear](#41algelin)
    2. [Estatística](#42estat)
    

## 1. Instalação  <a name="1instalacao"></a>

Como falamos antes, o NumPy nada mais é que uma biblioteca do Python. Dito isso, para instalarmos ele, fazemos de forma semelhante a qualquer outra biblioteca Python.

Entre as diversas formas de fazer isso, a mais simples é instalar o pacote Anaconda (https://www.anaconda.com/distribution/). Ele já vem com o Python e diversas bibliotecas científicas e de ciência de dados instaladas. Se preferir reinstalar depois, o anaconda provê também o gerenciador de pacotes Conda, e assim é possível intalar o NumPy através do terminal.
```
$ conda install numpy
```

Caso prefira, você também pode instalar via o gerenciador de pacotes nativo do Python, o `pip`.  Para isso, utilizamos o comando abaixo via terminal.
```
$ pip install numpy
```

Para quem for usuário com maior conhecimento de programação e computação científica, recomenda-se uma lida nas [instruções de instalação mais detalhadas do NumPy][NumPy_install]. 

O maior motivo para isso é o fato de que, por trás dos panos, o NumPy utiliza as chamadas "bibliotecas de álgebra linear aceleradas", que pode ser tanto a biblioteca Intel MKL quanto a biblioteca OpenBLAS. Em algumas situações, é importante escolher qual das duas será usada pela sua instalação do NumPy.

Embora existam questões de performance computacionais para essa escolha, existem também motivos de negócio. A biblioteca Intel MKL não é de código fonte aberto, e sua licença pode não permitir alguns tipos de distribuição do código que você esteja desenvolvendo com o NumPy.


## 2. Introdução ao NumPy  <a name="2introducao"></a>

A primeira coisa que precisamos fazer para usar o NumPy em um código, é importar a biblioteca. A importação funciona como qualquer outra biblioteca Python, porém o alias `np` para a biblioteca é amplamente utilizado pela comunidade de usuários do Python. A importação então é sempre feita da forma abaixo.

In [2]:
import numpy as np

Com esse alias, o nosso código fica bem menor, facilitando para outras pessoas entenderem ele depois. Como o alias é comum na comunidade, ele também não gera confusões, e permite sabermos sempre quando alguma operação feita é nativa do NumPy.


Na introdução, comentamos que a estrutura de dados básica do NumPy é um "array multidimensional". Esse objeto do NumPy se chama **ndarray**. Um mnemônico para ajudar a lembrar é lembrar pensar em "N Dimensões ARRAY", ou "NDARRAY". Basta lembrar que o "nd" significa "n-dimensional", pois também podemos ter tabelas multidimensionais.


Essa estrutura é semelhante aos arrays de outras linguagens de programação. Pode ser uma lista de valores, uma tabela, ou uma tabela de tabelas. O importante é que todos os valores são do mesmo "tipo". Se um deles é um número inteiro, todos serão. Se um deles for um float, todos serão. Esse tipo é chamado de **dtype**.

O mais comum é usarmos ndarrays como listas ou tabelas de valores.

No caso de uma lista, nós temos um ndarray de uma dimensão. Matematicamente, esse objeto é equivalente a um vetor.

O método mais comum de criar um ndarray é usando a função `np.array`. Assim, para criar nosso "vetor", usamos o comando abaixo.

In [ ]:
vetor = np.array([1, 2, 3])

print(vetor)

In [47]:
lista = [1, 2, 3]

type(lista)

list

In [45]:
lista = [1, 2, 3]

vetor = np.array(lista)

print(vetor)

[1 2 3]


Se olharmos o tipo da variável `vetor`, veremos que ela é do tipo `NumPy.ndarray`.

In [48]:
# Olhando o 'type'
type(vetor)

numpy.ndarray

Podemos criar também uma tabela com duas dimensões. Nesse caso, temos uma matriz.

In [49]:
matriz = [[1, 2], [3, 4]]

matriz

[[1, 2], [3, 4]]

In [50]:
matriz = np.array([[1, 2], [3, 4]])
print(matriz)

[[1 2]
 [3 4]]


É possível, também, aumentar o número de dimensões. Nesse caso, se tivermos 3 dimensões, por exemplo, teríamos uma lista de tabelas. Se forem 4 dimensões, então temos uma tabela cujos elementos são tabelas. Assim, quanto mais dimensões, nós vamos empilhando em uma lista objetos com menos dimensões. Se forem 5 dimensões, temos uma lista de ndarrays de 4 dimensões (ou uma lista de tabelas de tabelas).

Matematicamente, quando temos 3 dimensões ou mais, nós chamamos esse objeto de um tensor. 

In [51]:
tensor = np.array([[[1, 2], [3, 4]], [[1, 0],[0, 1]]])
print(tensor)

[[[1 2]
  [3 4]]

 [[1 0]
  [0 1]]]


Note que a variável `tensor` nada mais é que duas tabelas.

Uma representação visual de ndarrays podem ajudar a entender melhor o que está acontecendo.

![NumPy_ndarray](https://s3-sa-east-1.amazonaws.com/lcpi/b50bd331-732b-48a4-9d46-01f20c15ab29.png "ndarrays"){width="400" height="450"}

(**Fonte:** Imagem adaptada da original, disponível pela ABRACD [\[5\]](#5))

O *ndarray* é a estrutura de dados básica do NumPy, e a que usaremos sempre. A partir dela que toda a "matemágica" acontece. Todo o poder do NumPy vem da implementação desse tipo de array e as operações relacionadas, que são mais eficientes que usar variáveis do tipo `list` em Python (embora ndarrays sejam menos flexíveis). 

Esses objetos também são muito comuns em matemática, pois representam basicamente vetores e matrizes. Assim, é bem direto "vetorizar" nosso código escrevendo-o de forma bem parecida com como faríamos em notação matemática.

Obs: Falamos antes também de tensores. Não é importante entender o que eles são para poder usar o NumPy. Apenas cálculos muito específicos se utilizam da matemática de tensores. Para a maioria dos casos, basta ter a visão que demos acima, sobre como eles são basicamente "matrizes com 3 ou mais dimensões". Isso significa que eles podem ser uma lista de tabelas, uma tabela de tabelas, uma lista de tabelas de tabelas, uma tabela de tabelas de tabelas, e por aí vai...

### 2.1. Cuidados iniciais: Como copiar arrays  <a name="21copiar"></a>

Antes de começar a ver as propriedades básicas de um ndarray, é importante ter uma questão muito importante em mente. Assim como os arrays nativos do Python, devido à forma como o NumPy trabalha com ndarrays na memória do computador, eles se comportam da forma mostrada abaixo.

In [57]:
lista = [1, 2, 3]
lista_2 = lista.copy()

lista_2[0] = 20

print(lista)
print(lista_2)

[1, 2, 3]
[20, 2, 3]


In [64]:
lista_basica = [1, 2, 3]

a = np.array(lista_basica)
b = a
b

array([1, 2, 3])

In [59]:
b[0] = 100
b

array([100,   2,   3])

In [60]:
a

array([100,   2,   3])

Note que no bloco de código, a variável `a` foi modificada depois que alteramos a variável `b`! Isso acontece porque ambas as variáveis apontam para o mesmo endereço de memória do computador. Quando fazemos `b[0] = 100`, estamos alterando o valor do primeiro elemento de `b` na memória. Como `a[0]` aponta para o mesmo lugar na memória, ele vai passar a ver o valor novo. Logo, teremos que seu valor será `100`.

Por este motivo, sempre que queremos copiar um array de uma variável para outra, usamos o método `copy()`.

In [61]:
a = np.array([1, 2, 3])
b = a.copy()
b

array([1, 2, 3])

In [62]:
b[0] = 100
b

array([100,   2,   3])

In [63]:
a

array([1, 2, 3])

O método `copy()` copia todos os valores do array para um novo endereço de memória. Assim, a variável `b` passa a apontar para esse novo endereço, e evitamos o problema anterior.

### 2.2. Propriedades de ndarrays  <a name="22propriedades"></a>

#### Dimensão e formato

Como vimos antes, é possível criar um ndarray com diferentes dimensões e formatos. Cada ndarray tem os atributos `ndim` e `shape` que guardam estas informações. Logo, para sabermos como é o nosso array, basta acessar esses atributos.

In [86]:
array_teste = np.array([   [[1, 2, 3], [4, 5, 6]]  ])
array_teste

array([[[1, 2, 3],
        [4, 5, 6]]])

In [84]:
array_teste.shape 

(1, 2, 3)

In [66]:
vetor.shape

(3,)

In [65]:
print(vetor.ndim)
print(vetor.shape)
print(matriz.ndim)
print(matriz.shape)
print(tensor.ndim)
print(tensor.shape)

1
(3,)
2
(2, 2)
3
(2, 2, 2)


Isso é extremamente importante para nos ajudar quando temos um ndarray muito grande, e precisamos relembrar o quão grande. Além disso, esses atributos também nos ajudam quando queremos criar funções genéricas que atuem em ndarrays.

A partir do formato do array, podemos obter também o número de elementos. Porém, objetos ndarray já têm o atributo `size` para facilitar.

In [106]:
print(vetor.size)
print(matriz.size)
print(tensor.size)

3
4
8


In [107]:
before = np.array([[1,2,3,4,5,6,7,8], [1,2,3,4,5,6,7,8]])

before.reshape((4, 4))

16

Muitas vezes queremos mudar o formato de um array. Por exemplo, podemos querer transformar um vetor de 4 elementos em uma matriz 2x2. Para isso, utilizamos a função `reshape`.

In [108]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)
print(before.size)

(2, 4)
8


In [109]:
after = before.reshape((8)) # o novo array deve ter a mesma quantidade de elementos
after

array([1, 2, 3, 4, 5, 6, 7, 8])

In [110]:
after = before.reshape((1, 1, 8)) 
after

array([[[1, 2, 3, 4, 5, 6, 7, 8]]])

In [117]:
after = before.reshape(2, 2, 2)
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

Outra forma de obter arrays com dimensões ou formatos diferentes é juntar e empilhar arrays. Podemos tanto empilhar um array em cima do outro (um "empilhamento vertical") usando a função `np.vstack`, quanto tentar colocar um ao lado do outro (um "empilhamento horizontal") usando a função `np.hstack`.

In [120]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(v1.ndim)
print(v2.shape)

1
(4,)


In [128]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 4

In [ ]:
usuarios_admin [nome, sobrenome, idade]

usuarios_desen [nome, sobrenome, idade]

usuarios_teste [nome, sobrenome, idade]

usuarios [nome, sobrenome, idade]

In [ ]:
usuario1_dados_financeiros [cartao, limite, bandeira]

usuario1_dados_pessoais [nome, sobrenome]

usuario1[cartao, limite, bandeira, nome, sobrenome]

In [124]:
np.vstack([v1, v2, v2, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [130]:
v1 = np.array([[1,2,3,4], [5,6,7,8]])
v2 = np.array([5,6,7,8])

print(v1)
print(v2)

[[1 2 3 4]
 [5 6 7 8]]
[5 6 7 8]


In [133]:
np.hstack([v1, v2])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
h1 = np.array([[1, 1, 1, 1], [1, 1, 1, 1]])

h2 = np.zeros((2,2))

print(h1.shape)
print(h2.shape)


np.hstack((h1, h2))

É comum falarmos de cada dimensão de um ndarray como um "eixo". Assim, se um ndarray tem 3 dimensões, nós podemos falar da "1ª dimensão do array" (o eixo 0 do array), da "2ª dimensão do array" (o eixo 1 do array) e da "3ª dimensão do array" (eixo 2 do array). Assim, um ndarray com formato `(3, 3, 2)` seria uma lista ao longo do seu primeiro eixo (eixo 0). Essa lista seria composta por 3 matrizes de tamanho 3 x 2. De forma totalmente equivalente, a gente poderia pensar que ele é uma lista com 2 matrizes 3 x 3 ao longo do seu terceiro eixo (eixo 2). 

In [136]:
list(range(18))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]

In [141]:
a = np.array(range(18))  
b = a.reshape((2, 3, 3))

b


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

A variável `b` vai ser um "cubo" de valores, invés de uma tabela. Assim, o que muda é só qual eixo a gente está olhando.

![NumPy_ndarray](https://s3-sa-east-1.amazonaws.com/lcpi/1e527c6a-ea64-46e3-bd31-ffba06749000.png "ndarrays"){width="600" height="450"}

(**Fonte:** Imagem original Lets Code)

#### Tipos de dados e tamanho em memória

Um array do NumPy tem a propriedade `dtype`, que nos dá o tipo dos seus elementos mais básicos.

In [142]:
lista = [12, 13.6, 'Jorge', True]

lista

[12, 13.6, 'Jorge', True]

In [151]:
import numpy as np

vetor = np.array([1, 2, 3, 4, 5, 6, 7])

vetor.dtype

dtype('int32')

Quando nós construímos o ndarray, se não passarmos explicitamente qual é o `dtype`, ele infere a partir dos valores que passamos.

In [154]:
vetor = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0], dtype='int64')
vetor.dtype

dtype('int8')

Para passar esse parâmetro explicitamente, basta utilizar um segundo argumento na função `np.array`.

In [147]:
vetor = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.8], dtype=np.int32)
vetor.dtype

dtype('int32')

In [148]:
vetor

array([1, 2, 3, 4, 5, 6, 7])

Para esses arrays, nós dizemos que a consistência dos dados é **forte**. Isso significa que, se criarmos um vetor de números inteiros, por exemplo, então todos os elementos que colocarmos no nosso vetor **vai ser inteiro**.

Se tentarmos colocar um valor numérico de ponto flutuante, o NumPy vai automaticamente converter para um valor inteiro.

In [ ]:
a = np.array([1, 2, 3])
a[0] = 10
a

In [ ]:
a[0] = 1.23
a

O valor padrão de *dtype* depende do Python instalado. Se o Python instalado for de 64 bits, o padrão será tipos `int` ou `float` de 64 bits de memória (`int64` ou `float64`). Caso seu Python seja 32 bits, o padrão será `int32` e `float32`.

Essa diferença afeta a precisão dos cálculos. Quanto mais espaço em memória utilizado (maior o número de bits), maior a precisão.

Como o NumPy é feito para cálculos numéricos, ele precisa de grande controle sobre essa precisão. De fato, ele precisa de mais controle sobre isso do que o Python básico.

Devido a isso, os tipos de dados numéricos básicos do NumPy parecem com os do Python, mas em geral têm um número à direita. Esse número representa o seu nível de precisão computacional.

Alguns exemplos de tipos de dados do NumPy (e provavelmente os mais comuns) são:

* `np.int32`
* `np.int64`
* `np.float32`
* `np.float64`

Como exemplo, podemos criar uma outra array, `a16`, com o tipo inteiro de 16 bits.

In [1]:
[[1, 2, 3], [4, 5, 6]]

[[1, 2, 3], [4, 5, 6]]

In [21]:
2 ** 8

256

In [31]:
a8 = np.array([1, 2, 3], dtype="int32") # valores entre [-2**7+1 e 2**15 - 1] [-127, 127]
# np.int16 = "int16"
a8

array([1, 2, 3])

In [27]:
a8.ndim  

1

In [16]:
a8[0] = 130 

a8

C:\Users\jcham\AppData\Local\Temp\ipykernel_8764\938712127.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 130 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  a8[0] = 130


array([-126,    2,    3], dtype=int8)

Note que por ser um tipo diferente do padrão, ele ressalta ao mostrar o array na tela.

Para descobrir o espaço que cada elemento ocupa na memória, individualmente, podemos acessar o atributo `itemsize`.

In [28]:
a8.itemsize

2

In [29]:
a8.size 

3

In [32]:
a8.itemsize * a8.size

12

Ele retornou 2! Mas a gente não falou que era um tipo inteiro de "16 bits"?

O NumPy nos mostra o espaço em memória em bytes, e não em bits. Cada byte equivale a 8 bits. Logo, 16 bits são o mesmo que 2 bytes.

$\frac{16}{8} = 2$

Já se fizermos um array padrão em um Python de 64 bits, temos um `itemsize` de 8.

In [ ]:
a = np.array([1, 2, 3])
a.dtype

In [ ]:
a.itemsize

Isso pois o padrão de 64 bits equivale a 8 bytes.
$\frac{64}{8} = 8$

A quantidade de elementos multiplicado pelo tamanho de cada elemento em memória nos dará o tamanho total de bytes que o array inteiro ocupa na memória do computador.

In [ ]:
# quantidade de elementos total
a.size

In [ ]:
# tamanho em memória do vetor "a"
a.size * a.itemsize

Não precisamos, porém, ficar calculando esse valor se quisermos saber essa informação. Podemos simplesmente acessar o atributo `nbytes`, que representa o tamanho total em bytes ocupado pelo array.

In [ ]:
a.nbytes

**Observação**

Geralmente não é necessário reduzir o número de bits a não ser que você tenha certeza que um tamanho reduzido vai atender sua necessidade e você quer ser **extremamente** eficiente.

---

Podemos converter os tipos de dados do array do NumPy depois da sua criação de forma manual, usando a função `astype`.

In [38]:
a = np.array([1.0, 2.0, 3.888])

a.dtype

dtype('float64')

In [42]:
b = a.astype("int32")

b.dtype

dtype('int32')

In [43]:
b

array([1, 2, 3])

In [45]:
a.dtype

dtype('float64')

In [56]:
lista =  [ [1, 2, 3] , [4, 5, 6]  ]

# 2 dimensoes = matriz

array = np.array(lista, dtype = "int8") # dtype -> definir o tipo de dado de cada elemento

print(array.ndim) # numero de dimensoes

print(array.shape) # tamnaho de cada dimensao

print(array.size) # numero de elementos

print(array.dtype) # tipo de dado de cada elemento

print(array.itemsize) # tamanho de cada elemento em bytes

2
(2, 3)
6
int8
1


In [58]:
array_float = array.astype("float32")

print(array_float.dtype)

array_float

float32


array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

### 2.3. Acessando e modificando elementos (Indexing & Slicing)  <a name="23indexing"></a>

Vamos montar duas matrizes, uma usando Python e outra usando NumPy, para podermos comparar como nós acessamos os elementos de cada uma.
```python

In [111]:
np_mat = np.array([[1, 2,  3,  4,  5,  6,  7], 
              [8, 9, 10, 11, 12, 13, 14]])
print(np_mat)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [60]:
py_mat = [[1, 2,  3,  4,  5,  6,  7], 
          [8, 9, 10, 11, 12, 13, 14]]
    
print(py_mat)

[[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]]


Podemos acessar um elemento específico de forma similar a uma lista natural do Python, utilizando a sintaxe de colchetes. Porém, no NumPy, quando temos 2 ou mais dimensões, nós passamos a posição que queremos buscar atráves de números separados por vírgulas.

Se quisermos então pegar o número 13 nos arrays acima, que está na posição \[1,5\] (linha 1, coluna 5, lembrando que o Python começa os índices sempre pelo 0), no Python teríamos que usar a sintaxe abaixo.

In [67]:
# primeiro elemento : indice -> 0

# [] -> colchete
# {} -> chave

py_mat[1][-2]

13

Já para um ndarray com duas dimensões (2D), temos uma sintaxe um pouco mais simples.

In [63]:
np_mat[1, 5]

13

Além disso, todas as regras do Python são aplicáveis no NumPy. Usar números negativos, por exemplo, funciona como uma indexação de trás para frente.

In [70]:
np_mat[1, -3]

12

In [71]:
notas = np.array([1, 2,  3,  4,  5,  6,  7])

notas[-1]

7

In [72]:
notas = np.array([1, 2,  3,  4,  5,  6,  7])

notas[-1]

7

Para pegar uma linha inteira, podemos utilizar a sintaxe de `:` na coluna. Essa sintaxe pode ser lida como "todos os elementos deste eixo". Podemos ler então a sintaxe abaixo como "linha zero, todas as colunas".

In [73]:
np_mat

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [75]:
np_mat[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

Embora também poderíamos fazer de forma mais fácil essa indexação em específico.

In [ ]:
np_mat[0]

Porém, para pegar uma coluna, não tem jeito, precisamos usar `:`. A sintaxe abaixo pode ser lida como "todas as linhas, coluna 2".

In [76]:
np_mat

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [77]:
np_mat[:, 2]

array([ 3, 10])

O operador `:` é também conhecido como slicing (ou "fatiamento", em português), e pode ser usado para pegar intervalos de indices. Para isso, ele precisa de três parâmetros:
- start, o índice inicial do intervalo
- end, o índice final do intervalo
- step, quantos índices nós pulamos em cada passo dado para ir do *start* até o *end*.

Isso é feito no formato `[start:end:step]`. Neste caso, `step` é o tamanho do passo que vamos dar. Basicamente, ele diz quantos elementos devemos pular de cada vez. Como exemplo, podemos pegar do elemento 1 ao 6 pulando de 2 em 2 na linha 0.

In [80]:
np_mat

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [ ]:
# 

In [114]:
np_mat[0 , 0 : 3 : 2]

array([1, 3])

Novamente, ele também funciona com índice negativo.

In [100]:
np_mat[0, 1:-1:1]

array([2, 3, 4, 5, 6])

In [103]:
np_mat[:, 1:-1]

array([[ 2,  3,  4,  5,  6],
       [ 9, 10, 11, 12, 13]])

In [ ]:
np_mat[1,5]

Podemos usar essas indexações para alterar os elementos do array. Basta usar o operador `=` para atribuir um novo falar ao elemento daquela posição.

In [105]:
np_mat

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [104]:
np_mat[1,5]

13

In [106]:
np_mat[1,5] = 20
print(np_mat)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [107]:
np_mat[1,5]

20

Isso vale até para colunas ou linhas inteiras.

In [108]:
np_mat[:, 2] 

array([ 3, 10])

In [142]:
np_mat[:, 2] = 5

print(np_mat)

[[20  1  5  3  4  5  6]
 [ 7  8  5 10 11 12 13]
 [14 15  5 17 18 19 20]]


In [110]:
np_mat

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

In [130]:
np_mat = np.array([[0,   1,  2,  3,  4,  5,  6], 
                   [7,   8,  9, 10, 11, 12, 13],
                   [14, 15, 16, 17, 18, 19, 20]])

#  3,  4,  5
# 10, 11, 12

#np_mat[0:2, 3:6]  # [0:-1, 3:-1]

#  15, 20

# np_mat[2, 1: :5] # [2, 1:7:5]

np_mat[:, :]



array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])


Isso acontece por uma característica fundamental do array do NumPy:

<b><center>Ao alterar o pedaço recortado da matriz (o "slice" da matriz), você altera a matriz original.</center></b>

Juntando com o problema que vimos antes, de cópia de array, quando queremos copiar um slice de um array, temos que explicitamente usar o método `copy`.


In [156]:
# Lista padrao (slice gera copia)

a = [1,2,3]

b = a[:]

b[0] = 20

a

[1, 2, 3]

In [152]:
# Array numpy (slices nao geram copias)

np_mat = np.array([[0,   1,  2,  3,  4,  5,  6], 
                   [7,   8,  9, 10, 11, 12, 13],
                   [14, 15, 16, 17, 18, 19, 20]])

b = np_mat[:, :].copy()

b[1, :] = 20

b

array([[ 0,  1,  2,  3,  4,  5,  6],
       [20, 20, 20, 20, 20, 20, 20],
       [14, 15, 16, 17, 18, 19, 20]])

In [147]:
a = 'String'

a = 10

a

10

In [ ]:
a = np.array([1, 2, 3])
b = a[1:].copy()
b

In [ ]:
c = a[1:]
c

In [ ]:
c[0] = 5
c

In [ ]:
a

In [11]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

#a[0] # por indice

#a[1:3] # por slice

a[0 , 3] # por indices

a[0:2, 1:3] # por slices

array([[2, 3],
       [6, 7]])

### 2.4. Máscara Booleana e Seleção Avançada  <a name="24boolmask"></a>

Uma outra forma de seleção é por meio de uma lista de posições.

In [12]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

a[[1, 2, -1]]

array([2, 3, 9])

No caso de arrays multidimensionais, vamos ter que passar uma lista para cada dimensão. O NumPy nos retornará os elementos formados pelos pares (se 2D, se for 3D são trincas, se 4D quadras, etc.) dessas listas.

In [14]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(3,3)

a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
a[[1, 0], [2, 1]]

array([6, 2])

In [29]:
np_mat = np.array([[0,   1,  2,  3,  4,  5,  6], 
                   [7,   8,  9, 10, 11, 12, 13],
                   [14, 15, 16, 17, 18, 19, 20]])

# [1, 2, 18, 19]

# recuperei do processo X
lista_indice_linha = [0, 0, 2, 2]
lista_indice_coluna = [1, 2, 4, 5]

# colocar 100 nessas posições

#for indice in range(len(lista_indice_linha)):
#    np_mat[lista_indice_linha[indice], lista_indice_coluna[indice]] = 100

np_mat[lista_indice_linha, lista_indice_coluna] = 100

#np_mat[[0, 0, 2, 2], [1, 2, 4, 5]] = 100

np_mat

array([[  0, 100, 100,   3,   4,   5,   6],
       [  7,   8,   9,  10,  11,  12,  13],
       [ 14,  15,  16,  17, 100, 100,  20]])

Uma outra forma muito comum de selecionar elementos de um ndarray é usando o que chamamos de "máscara booleana". Ela nada mais é do que um array de elementos booleanos ("True" ou "False"). Tanto faz se for uma lista do Python ou um ndarray do NumPy. 

Assim, quando passamos essa máscara para um array do NumPy, ele nos retorna apenas as posições onde temos o valor "True".

In [30]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
a[[0, 1, 2, 7]]

array([1, 2, 3, 8])

In [32]:
a[[True, True, True, False, False, False, False, True, False]]

array([1, 2, 3, 8])

Note, no exemplo acima, que temos 3 posições onde nossa máscara possui valor "True". A posição 0, a posição 1, e a posição 7, que correspondem aos valores 1, 2, e 8, respectivamente.

Nós podemos gerar essa máscara a partir de comparações elemento a elemento de um ndarray. De fato, ao aplicar qualquer operador booleano, como

- `>`,
- `<`,
- `<=`,
- `>=`,
- `==`,

para comparar um ndarray com algum valor, o NumPy retorna um ndarray de valores booleanos. Esse novo ndarray vai ter o valor `True` nas posições onde a comparação do elemento original e esse valor separado for verdadeira. Teremos o valor `False` caso contrário.

Vamos ver um exemplo.

In [34]:
mat = np.array([1, 10, 20, 30]).reshape(2, 2)
mat

array([[ 1, 10],
       [20, 30]])

In [37]:
(mat >= 20) | (mat <= 5) 

array([[ True, False],
       [ True,  True]])

Podemos juntar os dois exemplos anteriores, de uso da máscara booleana como indexação e da criação de uma máscara, em uma única linha.


In [38]:
mat[(mat >= 20) | (mat <= 5)]

array([ 1, 20, 30])

In [47]:
mat = np.array([[0,   1,  2,  3,  4,  5,  6], 
                [7,   8,  9, 10, 11, 12, 13],
                [14, 15, 16, 17, 18, 19, 20]])

# [1, 2, 18, 19]

# [8, 9, 10, 11, 20]

mat[ ((mat >= 8) & (mat <=11)) |  (mat == 20)]

array([ 8,  9, 10, 11, 20])

In [52]:
# [1,  2,  3,  4,  5]   -> slice

# [1, 2, 3, 4, 5, 8, 9, 10, 11] 

mat[0, 1:6] # 5 colunas & 1 linha

mat[1, 1:5] # 4 colunas & 1 linha

np.hstack([mat[0, 1:6], mat[1, 1:5]])

array([ 1,  2,  3,  4,  5,  8,  9, 10, 11])

In [56]:
mat[((mat >= 1) & (mat <= 5)) | ((mat >= 8) & (mat <= 11))]

array([ 1,  2,  3,  4,  5,  8,  9, 10, 11])

In [54]:
[1,2,3,4,5] + [6,7,8,9] 
[6,7,8,9] 

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [55]:
np.concatenate([mat[0, 1:6], mat[1, 1:5]])

array([ 1,  2,  3,  4,  5,  8,  9, 10, 11])

In [61]:
array_3d = np.array([1,2,3,4,5,6,7,8]).reshape(2,2,2)

array_3d[[1], [1], [0]]


array_3d[array_3d > 5]


array([6, 7, 8])

In [ ]:
mat = np.array([[0,   1,  2,  3,  4,  5,  6], 
                [7,   8,  9, 10, 11, 12, 13],
                [14, 15, 16, 17, 18, 19, 20]])

Neste exemplo, temos como retorno um array com os elementos 20 e 30, como era esperado.

Podemos fazer operações semelhantes, mas restritos a seguir "linha a linha" ou "coluna a coluna". No nosso exemplo anterior, pode ser que queiramos todas as linhas onde existe um elemento com valor `10`. Outra opção seria pegar todas as colunas com pelo menos 1 elemento abaixo do valor `10`.

Para isso, usamos os métodos auxiliares `any` e `all`.

* any: se qualquer elemento do meu eixo for `True`, retorna um valor `True`
* all: se, e somente se, todos os elementos do meu eixo forem `True`, retorna `True`

Nas explicações, o "eixo" são as dimensões do ndarray, como discutido na sessão 2.2.

Vamos ver alguns exemplos.

O exemplo abaixo pega todas as linhas onde existe pelo menos um elemento com valor `10`.

In [62]:
mat = np.array([[0,   1,  2,  3,  4,  5,  6], 
                [7,   8,  9, 10, 11, 12, 13],
                [14, 15, 16, 17, 18, 19, 20]])

In [76]:
mat > 10

array([[False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [80]:
(mat > 4).all(axis=1) 

# axis = 1 -> retorna as linhas (filtrar)
# axis = 0 -> retorna as colunas (filtrar)

# all -> todos os elementos cumprem a condição
# any -> pelo menos um elemento cumpre a condição

array([False, False, False, False, False,  True,  True])

In [85]:
(mat > 10).any(axis=0)

array([ True,  True,  True,  True,  True,  True,  True])

In [96]:
mat[ (mat > 10).any(axis=1),  : ]

array([[ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

Por que usamos o eixo 1 nesse caso? Porque aqui, o eixo define por onde o NumPy vai "traversar" para avaliar o nosso ndarray.

O eixo 0 são as linhas. Assim, quando olhamos *ao longo do eixo 0*, nós estamos caminhando através das linhas. Se usássemos `(mat == 10).any(axis=0)`, o NumPy vai ver se tem elementos que sejam iguais a 10 **ao longo do eixo 0**. 

O processo então vai ser o seguinte:
- olha se `1 == 10`. Nesse caso, temos `False`. 
- o próximo elemento, **ao longo do eixo 0**, é o `20`.
- `20 == 10` também retorna `False`. Logo, nessa coluna, a resposta será `False`.
- segue para a próxima coluna.

Já quando usamos `(mat == 10).any(axis=1)`, ele olha **ao longo do eixo 1**, ou seja, ao longo das colunas. O processo fica:
- olha se `1 == 10`. Nesse caso, temos `False`. 
- o próximo elemento, **ao longo do eixo 1**, é o `10`.
- `10 == 10` retorna `True`. Logo, existe pelo menos um valor `True`. Então, para essa linha, retornamos o valor `True`.
- segue para a próxima linha.


Como um outro exemplo, se quisermos pegar as colunas onde todos os elements sejam maiores que `5`, podemos usar o `all`. A regra de qual eixo usar é igual.

In [ ]:
mat[:, (mat > 5).all(axis=0)]

Perceba que neste exemplo, nós colocamos dois pontos na primeira posição. Isso garante que pegamos todas as linhas, e olhamos a nossa máscara booleana apenas ao longo das colunas. Além disso, colocamos `axis=0`, para olhar ao longo do eixo 0.

Para nos ajudar a lembrar essa questão do parâmetro `axis`, podemos pensar que esse parâmetro define ao longo de qual eixo a função irá "esmagar" o nosso array.

In [93]:
new_mat = np.array([1, 2, 4, 5, 7, 8]).reshape(3, 2) 
new_mat

array([[1, 2],
       [4, 5],
       [7, 8]])

In [108]:
new_mat[(new_mat < 8).all(axis=1)] # Apenas as 2 primeiras linhas têm todos os elementos < 8

array([[1, 2],
       [4, 5]])

In [106]:
new_mat[:, (new_mat == 5).any(axis=0)] # Apenas a segunda coluna tem um elemento com valor 5

array([[2],
       [5],
       [8]])

In [ ]:
nome sexo idade

Jorge M   29
Maria F   20
Jose  M   25


Jorge M   29
Jose  M   25

#### Múltiplas condições

Similar ao `and` do python, nós podemos usar múltiplas condições para filtrar dados da nossa matriz com o operador `&`.


In [ ]:
mask = (mat > 10) & (mat <= 20)

mat[mask]

**Observação:** note que os parênteses, além de melhorarem a legibilidade, são necessárias devido a ordem de precedência dos operadores `>`, `&` e `<=`. Se não colocarmos os parênteses, dará um erro.

Além do `&`, também podemos fazer quaisquer operações booleanas básicas.

No caso do `or`, nós temos o operador `|`.


In [ ]:
mask = (mat == 1) | (mat >= 20)
mat[mask]

In [109]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

In [121]:
nota = 20
if (not (nota > 10)) | (nota > 5):  
    print("Entrouu")

Entrouu


In [115]:
# & = and
# | = or
# ~ = not

True

In [111]:
~(mat > 10)

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False, False],
       [False, False, False, False, False, False, False]])

No caso do `not`, nós temos o operador `~`.


In [127]:
mask = (mat == 1) & (mat >= 20)
mat[~mask]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

### 2.5. Métodos built-in de criação de arrays  <a name="25arraycreate"></a>

O NumPy já possui diversos métodos para gerar alguns arrays comuns mais conhecidos.
Isso nos ajuda imensamente a criar algumas matrizes padrões para fazer contas.

Primeiro, é possível gerar um array de zeros com qualquer formato.

In [128]:
np.zeros((2, 3)) # O argumento é o formato do ndarray resultante.

array([[0., 0., 0.],
       [0., 0., 0.]])

In [129]:
zeros = np.zeros((2, 2, 5), dtype='int32')

zeros

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

Para criar um array de uns, a sintaxe é semelhante.

In [130]:
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

Se invés de uma matriz apenas de uns, nós quisermos usar outro número, podemos fazer isso aproveitando o `np.ones`. Basta multiplicarmos a matriz pelo número que desejamos.

In [135]:
np.ones((2, 2), dtype="int8") * 50

array([[50, 50],
       [50, 50]], dtype=int8)

Mas o NumPy já tem uma opção mais direta, o `full`.

In [139]:
np.full((2, 2), 8, dtype="int8") # O primeiro argumento é o formato, o segundo é o número

array([[8, 8],
       [8, 8]], dtype=int8)

Também temos o `full_like`, que copia o formato de uma matriz que já tenha sido declarada antes.

In [142]:
np_mat = np.array([[1, 2,  3,  4,  5,  6,  7], 
                       [8, 9, 10, 11, 12, 13, 14]])

np.full_like(np_mat, 15)

array([[15, 15, 15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15]])

Outra função para criação de arrays é `np.repeat`. Ela repete um determinado array na direção do eixo escolhido.

Para um vetor de 1D, temos apenas 1 eixo, mas para matrizes, tempos dois. O eixo 0 é linha, o eixo 1 é coluna.

In [146]:
r1 = np.repeat(arr, 3)

r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

Para fazermos uma matriz, mudamos o formato da variável `arr` de (3,) para (1,3).

In [148]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [151]:
r2 = np.repeat(arr, 3, axis=1)
print(r2)

[[1 1 1 2 2 2 3 3 3]]


#### Criando arrays com listas de números

Um caso específico de criação de arrays é quando queremos gerar uma lista sequencial de números. Isso é muito comum, por exemplo, quando queremos calcular uma função matemática em vários pontos de uma única vez.

A primeira função do NumPy para criar essa sequência numérica é `np.arange`. Esta função retorna elementos igualmente espaçados por um step (que por padrão é 1) dentro de um certo intervalo.


In [152]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [153]:
arr = np.array(list(range(0, 10)))

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [154]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

A função `np.arange` é semelhante à função `range` do Python, porém permite que peguemos valores de ponto flutuante (números com decimal) dentro do nosso intervalo.

In [156]:
list(range(1, 10, 2))

[1, 3, 5, 7, 9]

In [157]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

Outro caso comum que esbarramos para criar uma lista sequencial é quando queremos escolher uma grande quantidade de pontos entre dois números. Por exemplo, pode ser que nós queiramos fazer um mesmo cálculo para 10 valores entre 3 e 7.

Neste caso, usamos a função `np.linspace`.

In [160]:
np.linspace(3, 8, num=4)

array([3.        , 4.66666667, 6.33333333, 8.        ])

#### Números decimais aleatórios

O NumPy tem um sub-módulo chamado `random` (cujas funções são acessadas usando o preâmbulo `np.random`). Nele, existe um conjunto de funções focadas em gerar arrays com números aleatórios.

Por exemplo, a função `np.random.random_sample` retorna valores aleatórios entre 0 e 1.

In [161]:
np.random.random_sample((4, 2)) # O argumento é o formato do array resultante.

array([[0.00538125, 0.46663157],
       [0.11198619, 0.47926039],
       [0.96091199, 0.82204145],
       [0.38012731, 0.42670345]])

A função `np.random.rand` é um "alias" da função de cima. Isso significa que, por trás dos panos, ela literalmente só executa a função `np.random.random_sample`.

Essa função existe para facilitar a migração de códigos de outras linguagens de computação numérica (especificamente, códigos de uma linguagem chamada MATLAB).

In [171]:
np.random.randint(1, 20+1, (10))

array([ 3, 11,  1, 16,  4, 19, 18, 16,  6, 15])

In [174]:
arr=  np.arange(1, 10, 2)

np.sum(arr)

25

Se quisermos criar um array de números inteiros abaixo de um certo valor, escolhidos ao acaso, usamos a função `np.random.randint`.

In [ ]:
np.random.randint(7, size=(3, 3)) # Números menores que 7, formato 3 x 3

Os argumentos principais da função `np.random.randint` são `low`, `high` e `size`, que definem o menor inteiro possível, o maior inteiro possível, e o tamanho do array resultante.


In [ ]:
np.random.randint(5, 10, (3,3))

Para incluir o 10 entre os valores possíveis, basta trocar o argumento high para 11.


## Exercícios

1. Escreva um programa NumPy para criar uma matriz 3x4 preenchida com valores de 10 a 21.
   
   A saida esperada seria [[10, 11, 12, 13], [14, 15, 16, 17], [18, 19, 20, 21]]

2. Escreva um programa NumPy para criar uma matriz bidimensional 8x5 de números aleatórios. Selecione números aleatórios entre 10 e 25.

3. Escreva um programa NumPy para criar uma matriz 10x10, na qual os elementos nas bordas serão iguais a 1 e no interior 0.

4. Usando como base o 'Exercício de aquecimento', compare quanto demora somar um vetor da forma convencional e usando Numpy.

## 3. Matemática com NumPy  <a name="3matematica"></a>

No início deste texto, nós introduzimos o NumPy como uma biblioteca muito utilizada para fazer cálculos numéricos. Vamos ver então as operações matemáticas disponíveis no NumPy.

A primeira coisa a se observar é que as operações matemáticas básicas, como usadas no Python, podem ser usadas também para ndarrays. Só temos que lembrar sempre que elas são aplicadas elemento a elemento.

In [183]:
vec1 = np.array([2., 4., 6., 8.])
vec2 = np.array([1., 2., 3., 4.])
vec1 + vec2                    # Soma

array([ 3.,  6.,  9., 12.])

In [184]:
vec1 - vec2                    # subtração

array([1., 2., 3., 4.])

In [185]:
vec1 * vec2                    # Multiplicação

array([ 2.,  8., 18., 32.])

In [186]:
vec1 / vec2                    # Divisão

array([2., 2., 2., 2.])

In [187]:
vec1 ** vec2                   # exponenciação 

array([2.000e+00, 1.600e+01, 2.160e+02, 4.096e+03])

A notação com este "e" minúsculo significa que o número está escrito em potências de 10. Assim, `4.096e+03` significa `4096` (pois multiplicamos o número por 1000, que é dez elevado a 3). Ainda nesta linha, `2.160e+02` significa `216`.

O NumPy também consegue fazer operações entre arrays e números (chamadas operações com escalares).

In [189]:
vec2

array([1., 2., 3., 4.])

In [196]:
vec2 + 2                # Somar

array([5., 6., 7., 8.])

In [197]:
vec2

array([3., 4., 5., 6.])

In [190]:
vec2 - 2                 # Subtrair

array([-1.,  0.,  1.,  2.])

In [191]:
vec2 * 2                 # Multiplicar

array([2., 4., 6., 8.])

In [192]:
vec2 / 2                 # Dividir

array([0.5, 1. , 1.5, 2. ])

In [194]:
vec2 ** 2                   # Potência (elevar a um número)

array([ 1.,  4.,  9., 16.])

In [195]:
vec2 = vec2 + 2                # Incrementar
vec2

array([3., 4., 5., 6.])

Agora uma dúvida é: se os nossos ndarrays tiverem formatos diferentes, então o NumPy apenas retorna um erro?

Depende do caso. Ele consegue fazer a operação se a diferença entre os formatos seguirem algumas regras que veremos abaixo. Nestes casos, ele faz o que chamamos de **Broadcasting**.

Se a diferença entre os formatos não seguirem as regrinhas necessárias para realizar broadcasting, então o NumPy retorna de fato um erro.


In [199]:
a = np.array([1, 2, 3])
b = np.array([2, 2])
a * b

array([2, 4])

### 3.1. Broadcasting  <a name="31broadcasting"></a>

O que fizemos, nas operações com escalar, é um tipo de broadcasting. Você pode imaginar que o que está acontecendo é o seguinte:
- pegue o seu número,
- crie um ndarray, de mesmo formato que o primeiro, mas cujos valores são o seu número.


![broadcasting01](https://NumPy.org/doc/stable/_images/broadcasting_1.png "broadcasting escalar")

(**Fonte:** Tutoriais oficiais do NumPy [\[2\]](#2))

Na imagem acima (que foi tirada dos tutoriais oficiais do NumPy), nota que o valor 2 é "esticado". Ele é repetido ao longo do eixo 0 até ter um ndarray de formato (3,).


Essa ideia pode ser generalizada. Sempre que fizer sentido "esticar" (ou repetir) o array menor até ele ficarcom o mesmo formato do maior, então o NumPy consegue realizar uma operação de broadcasting.


In [211]:
matrix = np.array([[0, 0, 0, 0],
                   [10, 10, 10, 10],
                   [20, 20, 20, 20],
                   [30, 30, 30, 30]])

vec = np.array([1, 2])

print(matrix)

print("vetor")
print(vec)

[[ 0  0  0  0]
 [10 10 10 10]
 [20 20 20 20]
 [30 30 30 30]]
vetor
[1 2]


In [212]:
matrix + vec

ValueError: operands could not be broadcast together with shapes (4,4) (2,) 

In [208]:
vec = np.array([[1, 2, 3, 4]])
               
np.repeat(vec.T, 3, axis=1)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

![broadcasting02](https://NumPy.org/doc/stable/_images/broadcasting_2.png "broadcasting array")

(**Fonte:** Tutoriais oficiais do NumPy [\[2\]](#2))

A imagem acima mostra o que está acontecendo no código de exemplo que demos.

Mas por que colocamos a expressão "sempre que fizer sentido"? O motivo é que a única coisa que o NumPy aceita fazer é repetir o array menor diversas vezes na direção de uma dimensão. Ele não reajusta o seu array!

![not_broadcasting](https://NumPy.org/doc/stable/_images/broadcasting_3.png "not broadcasting")

(**Fonte:** Tutoriais oficiais do NumPy [\[2\]](#2))

In [ ]:
matrix = np.array([[0, 0, 0],
                       [10, 10, 10],
                       [20, 20, 20],
                       [30, 30, 30]])
vec = np.array([1, 2, 3, 4])
matrix + vec

É interessante notar que essa "esticada" para realizar o broadcast só pode ser feita em 1 eixo. Mesmo que fosse possível copiar o array menor até ele ter o mesmo formato do array maior, se para isso precisarmos fazer copias ao longo de 2 eixos, então o NumPy retorna um erro.

In [ ]:
a = np.array([[1, 2, 3, 4],
              [3, 4, 5, 6],
              [7, 8, 9, 10]])
b = np.array([2, 2])
a * b

In [ ]:
b = np.array([[2, 2]])
a * b

### 3.2. Funções matemáticas  <a name="32funcoesmath"></a>

Além de fazer operações matemáticas entre arrays, também podemos usar funções matemáticas conhecidas. O NumPy possui milhares de funções já implementadas. Por exemplo, ele possui as funções trigonométricas.

Função seno:

In [213]:
x = np.array([1, 2, 3, 4])

np.sin(x)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

Função cosseno:

In [214]:
x = np.array([1, 2, 3, 4])
np.cos(x)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

O NumPy também possui o valor de constantes matemáticas comuns, como o π ("pi").

In [215]:
np.pi

3.141592653589793

In [216]:
x = np.array([0, np.pi / 2 , np.pi, 3 * np.pi / 2, 2 * np.pi])
np.sin(x)

array([ 0.0000000e+00,  1.0000000e+00,  1.2246468e-16, -1.0000000e+00,
       -2.4492936e-16])

Os valores `1.2246468e-16` e `-2.4492936e-16` representam o número zero. O motivo de não estar zerado é que nem todas as operações com números de ponto flutuante (números reais com decimal) conseguem ser perfeitamente representadas pelo computador. Números de ponto flutuante sempre tem um grau de imprecisão. Então dentro da precisão do nosso cálculo, esses valores são basicamente o mesmo que zero.
 
Depois das funções trigonométricas, vamos ver a função exponencial.


In [217]:
x = np.array([1, 2, 3, 4]) 
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [222]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [221]:
x ** 0.5

# raiz quadrada -> np.sqrt()   -  operador potencia ** (0.5)





array([1.        , 1.41421356, 1.73205081, 2.        ])

Também existe a constante "e" (número euleriano) no NumPy. De fato, a função exponencial `np.exp(x)` nada mais é do que o número euleriano elevado a x.
$$e^{x}$$

Assim, também podemos fazer a mesma conta abaixo.


In [223]:
x = np.array([1, 2, 3, 4])
np.e ** x

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

Como falamos, existem milhares de funções matemáticas nativamente no NumPy, e todas são muito úteis para fazermos cálculos matemáticos computacionais. Porém, se tentarmos listar todas, precisaríamos de um texto insanamente maior. Então melhor ficarmos só com uma ou outra mesmo.

Temos falado, ao longo do texto, sobre o poder e eficiência do NumPy. Do ponto de vista de escrever código, uma enorme vantagem do NumPy é que podemos escrever equações matemáticas complicadas para todos os elementos do nosso array da mesma forma que escreveriamos no papel. 

Aqui entra em foco a ideia de "operações vetorizadas", que encontramos antes. No fim das contas, conseguimos escrever tudo de forma vetorizada no NumPy.

Imagine a equação abaixo:
$$ e^{x} + sin(x) $$

Se quisermos achar o valor dela para diversos valores de "x" entre -1 e 2 no Python, teríamos que fazer um loop iterativo. No NumPy, a operação é mais clara e direta.

In [224]:
x = np.linspace(-1, 2, 11)

x

array([-1. , -0.7, -0.4, -0.1,  0.2,  0.5,  0.8,  1.1,  1.4,  1.7,  2. ])

In [225]:
np.exp(x) + np.sin(x)

array([-0.47359154, -0.14763238,  0.2809017 ,  0.805004  ,  1.42007209,
        2.12814681,  2.94289702,  3.89537338,  5.0406497 ,  6.4656122 ,
        8.29835353])

Por fim, o último conceito essencial de se conhecer quanto a operações matemáticas no NumPy é o de número infinito e de NaN (not a number).

O NumPy possui duas constantes, `np.inf` e `np.NaN` que representam um "número infinito" e um erro, respectivamente.

O "número infinito" é um valor de ponto flutuante que é maior que qualquer outro número. Se colocarmos um sinal negativo, ele vira "menos infinito", e passa a ser menor que qualquer outro número.


In [226]:
np.inf

inf

In [227]:
np.inf > 3823748932489

True

In [228]:
-np.inf < -9832743293278423

True

Já o NaN é um valor indefinido. Sempre que nossa operação não fizer sentido, o numpy retorna um NaN.


In [231]:
np.array([ np.float64(0) / np.float64(0) ])

C:\Users\jcham\AppData\Local\Temp\ipykernel_4724\294685839.py:1: RuntimeWarning: invalid value encountered in scalar divide
  np.array([ np.float64(0) / np.float64(0) ])


array([nan])

## 4. Álgebra Linear e Estatística básica  <a name="4algelinestat"></a>


### 4.1. Álgebra Linear  <a name="41algelin"></a>

Da definição do Wikipédia:

Álgebra linear é um ramo da matemática que surgiu do estudo detalhado de sistemas de equações lineares [...]. A álgebra linear utiliza alguns conceitos e estruturas fundamentais da matemática como vetores,[...] e matrizes.

Independente da definição exata, a questão é que a álgebra linear estuda vetores e matrizes. Como vimos até aqui, o NumPy opera de forma bastante análoga à vetores e matrizes.

O que não vimos ainda é como o NumPy nos permite também executar operações típicas da álgebra linear, como "produto entre matrizes".

De fato, o NumPy tem a capacidade de realizar um "produto escalar" entre vetores, de fazer o produto de uma matriz por um vetor, e de fazer o produto entre matrizes.


Vamos relembrar o que são essas operações. O produto escalar de dois vetores consiste em multiplicar os dois, elemento a elemento, e depois somar os resultados de cada par de elementos.

![inner_prod](https://s3-sa-east-1.amazonaws.com/lcpi/d331eb96-4d9e-4cf4-98f6-23fdd8bebf7a.png)

(Exemplo de produto escalar, ou "produto interno") <br>
(**Fonte:** Imagem original Lets Code)


A sintaxe do NumPy é dada abaixo.

In [ ]:
vec1 = np.array([1, 2, 3])
vec2 = np.array([2, 2, 3])

vec1.dot(vec2)

In [ ]:
np.sum(vec1 * vec2)

Também podemos usar o operador `@`.

In [ ]:
vec1 = np.array([1, 2, 3])
vec2 = np.array([2, 2, 3])
vec1 @ vec2

O produto de matriz e vetor é dado fazendo algo semelhante ao produto escalar. Para cada linha da matriz, a gente faz o produto escalar entre aquela linha e o vetor. O resultado então vai ser o elemento que se encontra na mesma posição da linha.

![matrix_vec](https://upload.wikimedia.org/wikipedia/commons/2/22/Matrix_vector_multiplication.svg)

(**Fonte:** Usuária Claudia4 do site Wikimedia Commons, disponível em https://upload.wikimedia.org/wikipedia/commons/2/22/Matrix_vector_multiplication.svg)


As possibilidades de sintaxe do NumPy seguem abaixo.

In [ ]:
matrix = np.array([[1, 1, 1],
                   [1, 2, 3],
                   [1, 1, 1],
                   [1, 1, 1]])

vec2 = np.array([2, 2, 3])

matrix.dot(vec2)

In [ ]:
matrix @ vec2

Na multiplicação entre matrizes, nós multiplicamos a linha da matriz da esquerda pela coluna da matriz da direita, elemento a elemento, e somamos o resultado (produto escalar entre a linha da matriz da esquerda com a coluna da matriz da direita) para obter uma nova matriz.

Neste caso, quando fazemos o produto interno da linha N com a coluna M, nós obtemos o elemento que ficará na posição (N,M) na nova matriz.

![matrix_mult01](https://upload.wikimedia.org/wikipedia/commons/d/d9/Hands_matrix_multiplication.svg)

![matrix_mult02](https://upload.wikimedia.org/wikipedia/commons/e/eb/Matrix_multiplication_diagram_2.svg){width="400", height="300"}

(**Fonte:** Usuários Guy vandegrift e Bilou do site Wikimedia Commons, disponíveis em
https://upload.wikimedia.org/wikipedia/commons/d/d9/Hands_matrix_multiplication.svg e https://upload.wikimedia.org/wikipedia/commons/2/22/Matrix_vector_multiplication.svg)


Como nos casos anteriores, abaixo temos a sintaxe do NumPy.

In [ ]:
matrix1 = np.array([[1, 1, 1],
                    [1, 2, 3],
                    [1, 1, 1]])
# 3 * 3

matrix2 = np.array([[1, 1, 1],
                    [1, 1, 1],
                    [2, 1, 1]])
# 3 * 3

# resultado= 3 * 3

matrix1.dot(matrix2)

In [ ]:
matrix1 @ matrix2

No campo da álgebra linear, existem algumas matrizes especiais muito úteis. O NumPy possui métodos de criação para a maioria delas.

A mais importante é a chamada matriz identidade. Ela é uma matriz quadrada (mesmo número de linhas e colunas) com diagonal 1, e os outros valores 0.

In [ ]:
np.identity(3)

Ela se chama identidade pois qualquer matriz multiplicada pela identidade (por produto de matrizes) dá a própria matriz.

In [ ]:
matrix1

In [ ]:
matrix1 @ np.identity(3)

Outra operação comum com matrizes é a transposição.

![transposition](https://s3-sa-east-1.amazonaws.com/lcpi/3d11b2c4-65cb-463a-9ccc-b858b065d2b3.png "Transposição")

(**Fonte:** Imagem original Lets Code)

A transposição pode ser feita com a função `np.transpose`.

In [ ]:
a

In [ ]:
np.transpose(a)

Outra forma é usando o atributo `T`:

In [ ]:
a.T

Operações mais específicas se encontram no módulo `linalg` do NumPy.

Um exemplo é encontrar o determinante de uma matriz. O determinante é um número característico de uma dada matriz, e que se relaciona com diversas propriedades dela.


In [ ]:
c = np.identity(3)
print(c)

In [ ]:
np.linalg.det(c)

Para encontrar todas as funções específicas de Álgebra Linear que têm no NumPy, você pode acessar o link https://numpy.org/doc/stable/reference/routines.linalg.html.

Algum exemplo de funções já implementadas na biblioteca:
- Traço
- Decomposição de vetores
- Autovalor/autovetor
- Norma de Matriz
- Inversa
- Etc...


### 4.2. Estatística  <a name="42estat"></a>

Por fim, o NumPy também possui várias funções básicas de estatística, como mínimo, máximo, média, mediana, etc.
```python

In [ ]:
stats = np.array([[1, 2, 3], [4, 5, 6]])

stats

In [ ]:
np.min(stats)

In [ ]:
np.max(stats)

In [ ]:
np.min(stats, axis=1) # Pega o menor valor de cada linha 

In [ ]:
np.max(stats, axis=0) # Pega o maior valor de cada coluna

In [ ]:
np.sum(stats, axis=0) # Faz a soma dos valores de cada coluna

In [ ]:
np.sum(stats) / stats.size

In [ ]:
np.mean(stats) # Valor médio de todos os elementos do array

In [ ]:
np.mean(stats, axis=0) # Valor médio de cada coluna do array

In [ ]:
np.mean(stats, axis=1) # Valor médio de cada linha do array

**Referências:**
--------------

1. <a name="1"></a> Documentação NumPy, disponível em https://NumPy.org/doc/stable/index.html ;
2. <a name="2"></a> Tutorial NumPy, disponível em https://NumPy.org/doc/stable/user/absolute_beginners.html ;
3. <a name="3"></a> Funções matemáticas do NumPy, disponível em https://numpy.org/doc/stable/reference/routines.math.html
4. <a name="4"></a> Álgebra linear com NumPy, disponível em https://numpy.org/doc/stable/reference/routines.linalg.html
5. <a name="5"></a> Tutorial NumPy da ABRACD, disponível em https://abracd.org/tutorial-numpy-os-primeiros-passos-em-computacao-numerica-e-tratamento-de-dados/


[NumPy_docs]: https://NumPy.org/doc/stable/index.html
[NumPy_install]: https://NumPy.org/install/
